export const BUSINESS = {
  name: "Ridge Line Roofing",
  legalName: "Ridge Line Roofing LLC",
  tagline: "Built for Northwest Arkansas Weather",
  phone: "(479) 334-9271",
  phoneHref: "tel:+14793349271",
  emergencyPhone: "(479) 334-9272",
  emergencyPhoneHref: "tel:+14793349272",
  email: "info@ridgelineroofing.com",
  address: {
    street: "2847 N College Ave, Suite 4",
    city: "Fayetteville",
    state: "AR",
    zip: "72703",
    full: "2847 N College Ave, Suite 4, Fayetteville, AR 72703",
  },
  license: "AR Roofing License #RF-20198",
  founded: 2011,
  url: "https://www.ridgelineroofing.com",
  hours: {
    weekday: "7:00 AM – 6:00 PM",
    saturday: "8:00 AM – 2:00 PM",
    sunday: "Closed (Emergency Available)",
    emergency: "24/7 Storm Damage Response",
  },
  social: {
    facebook: "https://www.facebook.com/ridgelineroofingNWA",
    instagram: "https://www.instagram.com/ridgelineroofing",
    google: "https://g.page/ridgelineroofing",
    yelp: "https://www.yelp.com/biz/ridge-line-roofing-fayetteville",
  },
  geo: {
    lat: 36.0822,
    lng: -94.1719,
  },
  certifications: [
    "GAF Master Elite® Contractor",
    "Owens Corning Preferred Contractor",
    "CertainTeed SELECT ShingleMaster™",
    "BBB A+ Accredited Business",
    "Licensed & Insured in Arkansas",
  ],
  stats: {
    yearsInBusiness: 13,
    roofsCompleted: "2,800+",
    fiveStarReviews: "580+",
    warrantyYears: 50,
  },
} as const;

export const SERVICE_AREAS = [
  {
    name: "Fayetteville",
    slug: "fayetteville",
    county: "Washington",
    pop: "95,000+",
    distance: "0 mi",
  },
  {
    name: "Bentonville",
    slug: "bentonville",
    county: "Benton",
    pop: "58,000+",
    distance: "25 mi",
  },
  {
    name: "Rogers",
    slug: "rogers",
    county: "Benton",
    pop: "72,000+",
    distance: "22 mi",
  },
  {
    name: "Springdale",
    slug: "springdale",
    county: "Washington",
    pop: "87,000+",
    distance: "12 mi",
  },
  {
    name: "Bella Vista",
    slug: "bella-vista",
    county: "Benton",
    pop: "30,000+",
    distance: "35 mi",
  },
  {
    name: "Centerton",
    slug: "centerton",
    county: "Benton",
    pop: "18,000+",
    distance: "28 mi",
  },
  {
    name: "Lowell",
    slug: "lowell",
    county: "Benton",
    pop: "10,000+",
    distance: "18 mi",
  },
  {
    name: "Siloam Springs",
    slug: "siloam-springs",
    county: "Benton",
    pop: "17,000+",
    distance: "30 mi",
  },
  {
    name: "Farmington",
    slug: "farmington",
    county: "Washington",
    pop: "8,000+",
    distance: "8 mi",
  },
  {
    name: "Prairie Grove",
    slug: "prairie-grove",
    county: "Washington",
    pop: "7,000+",
    distance: "14 mi",
  },
  {
    name: "Lincoln",
    slug: "lincoln",
    county: "Washington",
    pop: "2,800+",
    distance: "16 mi",
  },
  {
    name: "Tontitown",
    slug: "tontitown",
    county: "Washington",
    pop: "4,200+",
    distance: "10 mi",
  },
  {
    name: "Elm Springs",
    slug: "elm-springs",
    county: "Washington",
    pop: "5,500+",
    distance: "15 mi",
  },
  {
    name: "Cave Springs",
    slug: "cave-springs",
    county: "Benton",
    pop: "5,000+",
    distance: "20 mi",
  },
  {
    name: "Pea Ridge",
    slug: "pea-ridge",
    county: "Benton",
    pop: "6,500+",
    distance: "28 mi",
  },
  {
    name: "Gravette",
    slug: "gravette",
    county: "Benton",
    pop: "3,500+",
    distance: "34 mi",
  },
  {
    name: "West Fork",
    slug: "west-fork",
    county: "Washington",
    pop: "2,500+",
    distance: "12 mi",
  },
  {
    name: "Greenland",
    slug: "greenland",
    county: "Washington",
    pop: "1,400+",
    distance: "10 mi",
  },
  {
    name: "Elkins",
    slug: "elkins",
    county: "Washington",
    pop: "3,200+",
    distance: "12 mi",
  },
  {
    name: "Goshen",
    slug: "goshen",
    county: "Washington",
    pop: "2,300+",
    distance: "8 mi",
  },
  {
    name: "Johnson",
    slug: "johnson",
    county: "Washington",
    pop: "4,000+",
    distance: "5 mi",
  },
] as const;

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  {
    label: "Services",
    href: "/services",
    children: [
      { label: "Residential Roofing", href: "/services/residential" },
      { label: "Storm Damage Repair", href: "/storm-damage" },
      { label: "Insurance Claims", href: "/insurance-claims" },
    ],
  },
  { label: "Financing", href: "/financing" },
  { label: "Gallery", href: "/gallery" },
  { label: "Reviews", href: "/testimonials" },
  { label: "Service Areas", href: "/service-areas" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
] as const;

export const TESTIMONIALS = [
  {
    name: "Sarah Mitchell",
    location: "Fayetteville, AR",
    rating: 5,
    text: "After the April hailstorm took out half the shingles on our roof, Ridge Line had a crew out the next morning. They handled everything with our insurance company and we had a brand-new roof within the week. Couldn't be happier.",
    date: "2025-06-14",
    service: "Storm Damage Repair",
  },
  {
    name: "Marcus & Tina Johnson",
    location: "Rogers, AR",
    rating: 5,
    text: "We'd been putting off a full replacement for two years. Ridge Line walked us through the financing options and the entire process was painless. The crew was professional, cleaned up everything, and the roof looks incredible.",
    date: "2025-08-22",
    service: "Full Roof Replacement",
  },
  {
    name: "David Hernandez",
    location: "Bentonville, AR",
    rating: 5,
    text: "Third time using Ridge Line. First was a small leak repair, then storm damage, now a full replacement on our rental property. Consistent quality every single time. They're the only roofer I trust in NWA.",
    date: "2025-10-03",
    service: "Residential Roofing",
  },
  {
    name: "Karen O'Brien",
    location: "Springdale, AR",
    rating: 5,
    text: "The insurance claim process was a nightmare until Ridge Line stepped in. They knew exactly what the adjuster needed to see, documented everything, and got our claim approved for the full replacement. Worth every penny.",
    date: "2025-11-18",
    service: "Insurance Claims",
  },
  {
    name: "James & Patty Reynolds",
    location: "Prairie Grove, AR",
    rating: 5,
    text: "From the initial inspection to the final walkthrough, Ridge Line was transparent about every cost and timeline. No surprises, no hidden fees. They finished a day ahead of schedule. That's rare in this industry.",
    date: "2026-01-09",
    service: "Full Roof Replacement",
  },
  {
    name: "Angela Whitfield",
    location: "Bella Vista, AR",
    rating: 5,
    text: "Called at 10pm during a severe storm because water was coming through our ceiling. They had someone out first thing the next morning with a tarp, and started the full repair two days later. That kind of responsiveness means everything.",
    date: "2026-02-27",
    service: "Emergency Storm Repair",
  },
] as const;
